spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 51b1f0f7-8a62-4b43-8be9-42892b02bb10
    sentinel:
      transport:
        dashboard: localhost:7070
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hu_shop_goods?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8092
elasticsearch:
  ips: 127.0.0.1:9200



      

      