server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway从nacos中获取服务信息
      routes:
      - id: good-route
          uri: lb://service-good
          predicates:
          - Path=/service-good/**
          filters:
          - RewritePath=/service-good/(?<segment>.*), /$\{segment}
      - id: order-route
          uri: lb://service-order
          predicates:
          - Path=/service-order/**
          filters:
          - RewritePath=/service-order/(?<segment>.*), /$\{segment}
       
      
       
      
    
      