spring:
  cloud:
    nacos:
     discovery:
       server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:7070

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
server:
  port: 8092